// Bob language codes, not provider-specific ISO aliases.
module.exports = {
  "auto": "Auto",
  "zh-Hans": "Simplified Chinese",
  "zh-Hant": "Traditional Chinese",
  "yue": "Cantonese",
  "wyw": "Classical Chinese",
  "en": "English",
  "ja": "Japanese",
  "ko": "Korean",
  "fr": "French",
  "de": "German",
  "es": "Spanish",
  "it": "Italian",
  "ru": "Russian",
  "pt": "Portuguese",
  "nl": "Dutch",
  "pl": "Polish",
  "ar": "Arabic",
  "af": "Afrikaans",
  "bg": "Bulgarian",
  "ca": "Catalan",
  "cs": "Czech",
  "da": "Danish",
  "el": "Greek",
  "et": "Estonian",
  "fa": "Persian",
  "fi": "Finnish",
  "he": "Hebrew",
  "hi": "Hindi",
  "hr": "Croatian",
  "hu": "Hungarian",
  "id": "Indonesian",
  "lt": "Lithuanian",
  "lv": "Latvian",
  "ms": "Malay",
  "no": "Norwegian",
  "ro": "Romanian",
  "sk": "Slovak",
  "sl": "Slovenian",
  "sr": "Serbian",
  "sv": "Swedish",
  "th": "Thai",
  "tr": "Turkish",
  "uk": "Ukrainian",
  "ur": "Urdu",
  "vi": "Vietnamese"
};
